// Labels je Enum-Wert (DATENMODELL §4): `de` = Admin-/Anzeige-Label Deutsch, `en` = Anzeige-Label Englisch
// (Pflicht für öffentlich sichtbare Enums, siehe PUBLIC_ENUMS). Reines Modul, auch im Browser nutzbar.
import * as E from './enums'

export interface EnumLabel {
  de: string
  en?: string
  /** Abweichendes Label für Kund:innen (z. B. Bestellstatus, KONZEPT §5.3). */
  customerDe?: string
  customerEn?: string
}

type Labels<T extends string | number> = Record<T, EnumLabel>
const l = (de: string, en?: string): EnumLabel => (en === undefined ? { de } : { de, en })

const countryNames = (lang: 'de' | 'en') => new Intl.DisplayNames([lang], { type: 'region' })
const COUNTRY_LABELS = Object.fromEntries(
  E.COUNTRY_CODES.map((c) => [c, l(countryNames('de').of(c) ?? c, countryNames('en').of(c) ?? c)]),
) as Labels<E.CountryCode>

const FIBER_LABELS: Labels<E.TextileFiber> = {
  wool: l('Wolle', 'wool'),
  alpaca: l('Alpaka', 'alpaca'),
  llama: l('Lama', 'llama'),
  camel: l('Kamel', 'camel'),
  cashmere: l('Kaschmir', 'cashmere'),
  mohair: l('Mohair', 'mohair'),
  angora: l('Angora', 'angora'),
  vicuna: l('Vikunja', 'vicuna'),
  yak: l('Yak', 'yak'),
  guanaco: l('Guanako', 'guanaco'),
  cashgora: l('Kaschgora', 'cashgora'),
  beaver: l('Biber', 'beaver'),
  otter: l('Fischotter', 'otter'),
  animal_hair: l('Tierhaar', 'animal hair'),
  horsehair: l('Rosshaar', 'horsehair'),
  silk: l('Seide', 'silk'),
  cotton: l('Baumwolle', 'cotton'),
  kapok: l('Kapok', 'kapok'),
  flax: l('Leinen (Flachs)', 'flax (linen)'),
  hemp: l('Hanf', 'hemp'),
  jute: l('Jute', 'jute'),
  abaca: l('Manila', 'abaca (Manila)'),
  alfa: l('Alfa', 'alfa'),
  coir: l('Kokos', 'coir (coconut)'),
  broom: l('Ginster', 'broom'),
  ramie: l('Ramie', 'ramie'),
  sisal: l('Sisal', 'sisal'),
  sunn: l('Sunn', 'sunn'),
  henequen: l('Henequen', 'henequen'),
  maguey: l('Maguey', 'maguey'),
  acetate: l('Acetat', 'acetate'),
  alginate: l('Alginat', 'alginate'),
  cupro: l('Cupro', 'cupro'),
  modal: l('Modal', 'modal'),
  protein: l('Regenerierte Proteinfaser', 'protein'),
  triacetate: l('Triacetat', 'triacetate'),
  viscose: l('Viskose', 'viscose'),
  acrylic: l('Polyacryl', 'acrylic'),
  chlorofibre: l('Polychlorid', 'chlorofibre'),
  fluorofibre: l('Fluorfaser', 'fluorofibre'),
  modacrylic: l('Modacryl', 'modacrylic'),
  polyamide: l('Polyamid', 'polyamide'),
  aramid: l('Aramid', 'aramid'),
  polyimide: l('Polyimid', 'polyimide'),
  lyocell: l('Lyocell', 'lyocell'),
  polylactide: l('Polylactid', 'polylactide'),
  polyester: l('Polyester', 'polyester'),
  polyethylene: l('Polyethylen', 'polyethylene'),
  polypropylene: l('Polypropylen', 'polypropylene'),
  polycarbamide: l('Polyharnstoff', 'polycarbamide'),
  polyurethane: l('Polyurethan', 'polyurethane'),
  vinylal: l('Vinylal', 'vinylal'),
  trivinyl: l('Trivinyl', 'trivinyl'),
  elastodiene: l('Elastodien', 'elastodiene'),
  elastane: l('Elasthan', 'elastane'),
  glass_fibre: l('Glasfaser', 'glass fibre'),
  metal_fibre: l('Metallfaser', 'metal fibre'),
  paper_fibre: l('Papierfaser', 'paper fibre'),
  elastomultiester: l('Elastomultiester', 'elastomultiester'),
  elastolefin: l('Elastolefin', 'elastolefin'),
  melamine: l('Melamin', 'melamine'),
  pp_pa_bicomponent: l(
    'Polypropylen/Polyamid-Bikomponentenfaser',
    'polypropylene/polyamide bicomponent',
  ),
  polyacrylate: l('Polyacrylat', 'polyacrylate'),
  other_fibres: l('sonstige Fasern', 'other fibres'),
}

const AUDIT_LABELS: Labels<E.AuditAction> = {
  product_created: l('Stück angelegt'),
  product_published: l('Stück online gestellt'),
  product_status_changed: l('Status des Stücks geändert'),
  product_price_changed: l('Preis geändert'),
  product_offline_sold: l('offline verkauft'),
  product_adopted: l('Beispielstück übernommen'),
  product_deleted: l('Stück gelöscht'),
  reservation_conflict: l('Reservierungskonflikt'),
  order_created: l('Bestellung angelegt'),
  order_status_changed: l('Bestellstatus geändert'),
  order_address_changed: l('Adresse geändert'),
  order_status_link_rotated: l('Status-Link erneuert'),
  order_refund_created: l('Erstattung angelegt'),
  order_refund_failed: l('Erstattung gescheitert'),
  packing_photo_skipped: l('Packfoto übersprungen'),
  carrier_consent_withdrawn: l('Einwilligung DHL-Weitergabe widerrufen'),
  complaint_changed: l('Reklamation geändert'),
  invoice_issued: l('Rechnung ausgestellt'),
  credit_note_issued: l('Gutschrift ausgestellt'),
  withdrawal_received: l('Widerruf eingegangen'),
  withdrawal_matched: l('Widerruf zugeordnet'),
  withdrawal_status_changed: l('Widerrufsstatus geändert'),
  legal_text_activated: l('Rechtstext aktiviert'),
  legal_text_superseded: l('Rechtstext ersetzt'),
  legal_snippet_activated: l('Rechtsbaustein aktiviert'),
  legal_snippet_superseded: l('Rechtsbaustein ersetzt'),
  legal_review_confirmed: l('Rechtstext-Prüfung bestätigt'),
  settings_changed: l('Einstellungen geändert'),
  tax_mode_changed: l('Steuermodus geändert'),
  gallery_published: l('Galeriefoto veröffentlicht'),
  gallery_consent_withdrawn: l('Einwilligung Galeriefoto widerrufen'),
  inquiry_status_changed: l('Anfragestatus geändert'),
  inquiry_deleted: l('Anfrage gelöscht'),
  private_upload_deleted: l('private Datei gelöscht'),
  order_anonymized: l('Bestellung anonymisiert'),
  data_exported: l('Daten exportiert'),
  legal_hold_changed: l('Aufbewahrungssperre geändert'),
  processing_restricted: l('Verarbeitung eingeschränkt'),
  privacy_request_changed: l('Datenschutz-Anfrage geändert'),
  retention_setting_changed: l('Aufbewahrungsfrist geändert'),
  seed_imported: l('Beispieldaten eingespielt'),
  seed_removed: l('Beispieldaten entfernt'),
  login_succeeded: l('Anmeldung'),
  password_reset_requested: l('Passwort-Zurücksetzen angefordert'),
}

const EMAIL_TEMPLATE_LABELS: Labels<E.EmailTemplate> = {
  order_confirmation: l('M01 Bestellbestätigung'),
  prepayment_instructions: l('M02 Vorkasse – Zahlungsinformationen'),
  prepayment_reminder: l('M03 Vorkasse – Erinnerung'),
  prepayment_cancelled: l('M04 Vorkasse – Stornierung'),
  prepayment_received: l('M05 Zahlung erhalten'),
  order_shipped: l('M06 Versandbestätigung'),
  pickup_ready: l('M07 Abholbereit'),
  withdrawal_receipt: l('M08 Eingangsbestätigung Widerruf'),
  refund_confirmation: l('M09 Erstattung'),
  oversold_apology: l('M10 Stück leider schon weg'),
  inquiry_receipt: l('M11 Eingangsbestätigung Anfrage'),
  complaint_repair_choice: l('M12 Reklamation – Wahl der Nacherfüllung'),
  dispute_vsbg: l('M13 Hinweis Streitbeilegung (§ 37 VSBG)'),
  privacy_access_response: l('M14 Datenschutz – Auskunft'),
  privacy_erasure_response: l('M15 Datenschutz – Löschung/Einschränkung'),
  consent_withdrawal_confirmation: l('M16 Bestätigung Einwilligungswiderruf'),
  admin_order_placed: l('A01/A02 Neue Bestellung'),
  admin_prepayment_cancelled: l('A03 Vorkasse storniert'),
  admin_withdrawal_received: l('A04 Widerruf eingegangen'),
  admin_inquiry_received: l('A05 Neue Anfrage'),
  admin_oversold: l('A06 Stück doppelt bezahlt'),
  admin_dispute_opened: l('A07 Zahlung angefochten'),
  admin_refund_failed: l('A08 Erstattung gescheitert'),
  admin_revenue_guard: l('A09 Umsatz-Wächter'),
  admin_legal_review_due: l('A10 Rechtstexte prüfen'),
  admin_monthly_close: l('A11 Monatsabschluss'),
  admin_alert: l('A12 Technischer Hinweis'),
  admin_withdrawal_deadline: l('A13 Widerrufsfrist'),
  admin_password_reset: l('A17 Passwort zurücksetzen'),
  admin_privacy_request_due: l('A14 Datenschutz-Anfrage fällig'),
  admin_legal_hold_review: l('A15 Aufbewahrungssperre prüfen'),
  admin_compliance_docs_review: l('A16 Nachweise prüfen'),
}

const SNIPPET_LABELS = Object.fromEntries(
  E.LEGAL_SNIPPET_KEYS.map((k) => [k, l(`Baustein ${k}`)]),
) as Labels<E.LegalSnippetKey>

export const ENUM_LABELS = {
  LOCALES: { de: l('Deutsch', 'German'), en: l('Englisch', 'English') } satisfies Labels<E.Locale>,
  PRODUCT_CATEGORIES: {
    keramik: l('Keramik', 'Ceramics'),
    textil: l('Textil', 'Textiles'),
    cap: l('Caps', 'Caps'),
    zeichnung: l('Zeichnungen', 'Drawings'),
    schmuck: l('Schmuck', 'Jewellery'),
    sonstiges: l('Sonstiges', 'Other'),
  } satisfies Labels<E.ProductCategory>,
  PRODUCT_STATUSES: {
    draft: l('Entwurf', 'Draft'),
    available: l('online', 'Available'),
    reserved: l('reserviert', 'Reserved'),
    sold: l('verkauft', 'Sold'),
    archived: l('ausgeblendet', 'Hidden'),
  } satisfies Labels<E.ProductStatus>,
  SOLD_CHANNELS: {
    online: l('online', 'online'),
    pickup: l('Abholung', 'pickup'),
    offline: l('offline (Flohmarkt)', 'offline'),
  } satisfies Labels<E.SoldChannel>,
  SHIPPING_CLASSES: {
    brief: l('Brief', 'Letter'),
    paket_klein: l('Paket klein', 'Small parcel'),
    keramik: l('Keramik-Paket', 'Ceramics parcel'),
    nur_abholung: l('nur Abholung', 'Pickup only'),
  } satisfies Labels<E.ShippingClass>,
  SHIPPING_ZONES: {
    DE: l('Deutschland', 'Germany'),
    EU: l('EU', 'EU'),
    CH: l('Schweiz', 'Switzerland'),
  } satisfies Labels<E.ShippingZone>,
  FOOD_CONTACT: {
    deko: l('Deko – nicht für Lebensmittel', 'Decorative – not for food use'),
    lebensmittelecht: l(
      'lebensmittelecht (Konformitätserklärung)',
      'food-safe (declaration of conformity)',
    ),
  } satisfies Labels<E.FoodContact>,
  VAT_CATEGORIES: {
    standard: l('Regelsatz (19 %)', 'standard rate'),
    reduced_art: l('ermäßigt, echte Kunst (7 %)', 'reduced rate, original art'),
  } satisfies Labels<E.VatCategory>,
  TEXTILE_CONDITIONS: {
    like_new: l('wie neu', 'like new'),
    very_good: l('sehr gut', 'very good'),
    good: l('gut', 'good'),
    worn: l('deutliche Gebrauchsspuren', 'visible signs of wear'),
  } satisfies Labels<E.TextileCondition>,
  FIBER_COMPONENTS: {
    main: l('Hauptstoff', 'main fabric'),
    lining: l('Futter', 'lining'),
    trim: l('Besatz', 'trim'),
    other: l('Sonstiges', 'other'),
  } satisfies Labels<E.FiberComponent>,
  TEXTILE_FIBERS: FIBER_LABELS,
  EN_TRANSLATION_STATUSES: {
    missing: l('fehlt'),
    machine: l('maschinell übersetzt'),
    reviewed: l('geprüft'),
  } satisfies Labels<E.EnTranslationStatus>,
  DEVIATION_DECISIONS: {
    none: l('Geprüft: keine Abweichung'),
    described: l('Abweichung beschrieben'),
  } satisfies Labels<E.DeviationDecision>,
  CHECKOUT_STATUSES: {
    open: l('offen'),
    confirming: l('Zahlung wird bestätigt'),
    completed: l('abgeschlossen'),
    expired: l('abgelaufen'),
    cancelled: l('abgebrochen'),
    failed: l('Zahlung gescheitert'),
  } satisfies Labels<E.CheckoutStatus>,
  CHECKOUT_PAYMENT_CHOICES: {
    stripe: l('Karte, Apple Pay, Google Pay, PayPal', 'Card, Apple Pay, Google Pay, PayPal'),
    prepayment: l('Vorkasse (Überweisung)', 'Bank transfer (prepayment)'),
  } satisfies Labels<E.CheckoutPaymentChoice>,
  CHECKOUT_CLOSE_REASONS: {
    reservation_expired: l('Reservierung abgelaufen'),
    cart_changed: l('Warenkorb geändert'),
    replaced: l('durch neue Kasse ersetzt'),
    payment_failed: l('Zahlung gescheitert'),
    checkout_error: l('Fehler in der Kasse'),
    sold_offline: l('offline verkauft'),
  } satisfies Labels<E.CheckoutCloseReason>,
  RESERVATION_SOURCES: {
    checkout_session: l('Kasse'),
    prepayment: l('Vorkasse'),
  } satisfies Labels<E.ReservationSource>,
  RESERVATION_STATUSES: {
    active: l('aktiv'),
    converted: l('verkauft'),
    released: l('freigegeben'),
  } satisfies Labels<E.ReservationStatus>,
  RESERVATION_RELEASE_REASONS: {
    session_expired: l('Kasse abgelaufen'),
    payment_failed: l('Zahlung gescheitert'),
    customer_cancelled: l('von Kund:in abgebrochen'),
    prepayment_overdue: l('Vorkasse nicht bezahlt'),
    order_cancelled: l('Bestellung storniert'),
    checkout_error: l('Fehler in der Kasse'),
    admin: l('von Hand'),
  } satisfies Labels<E.ReservationReleaseReason>,
  FULFILLMENT_METHODS: {
    shipping: l('Versand', 'Shipping'),
    pickup: l('Abholung in Berlin', 'Pickup in Berlin'),
  } satisfies Labels<E.FulfillmentMethod>,
  PAYMENT_METHODS: {
    card: l('Karte / Apple Pay / Google Pay', 'Card / Apple Pay / Google Pay'),
    paypal: l('PayPal', 'PayPal'),
    prepayment: l('Vorkasse (Überweisung)', 'Bank transfer (prepayment)'),
  } satisfies Labels<E.PaymentMethod>,
  PAYMENT_PROVIDERS: {
    stripe: l('Stripe'),
    mock: l('Test (Mock)'),
    bank_transfer: l('Überweisung'),
  } satisfies Labels<E.PaymentProvider>,
  ORDER_STATUSES: {
    awaiting_prepayment: {
      de: 'Vorkasse offen',
      customerDe: 'Warten auf Überweisung',
      en: 'Awaiting bank transfer',
    },
    paid: { de: 'bezahlt', customerDe: 'Bezahlt', en: 'Paid' },
    packed: { de: 'gepackt', customerDe: 'Wird verpackt', en: 'Being packed' },
    shipped: { de: 'versendet', customerDe: 'Unterwegs', en: 'On its way' },
    ready_for_pickup: {
      de: 'bereit zur Abholung',
      customerDe: 'Abholbereit',
      en: 'Ready for pickup',
    },
    picked_up: { de: 'abgeholt', customerDe: 'Abgeholt', en: 'Picked up' },
    delivered: { de: 'zugestellt', customerDe: 'Zugestellt', en: 'Delivered' },
    cancelled: { de: 'storniert', customerDe: 'Storniert', en: 'Cancelled' },
    withdrawal_received: {
      de: 'Widerruf eingegangen',
      customerDe: 'Widerruf eingegangen',
      en: 'Withdrawal received',
    },
    return_received: {
      de: 'Ware zurück',
      customerDe: 'Rücksendung angekommen',
      en: 'Return received',
    },
    refunded: { de: 'erstattet', customerDe: 'Erstattet', en: 'Refunded' },
    partially_refunded: {
      de: 'teilweise erstattet',
      customerDe: 'Teilweise erstattet',
      en: 'Partially refunded',
    },
    disputed: { de: 'angefochten', en: 'Disputed' },
  } satisfies Labels<E.OrderStatus>,
  ORDER_CANCEL_REASONS: {
    payment_timeout: l('Zahlungsfrist abgelaufen', 'payment deadline passed'),
    admin: l('von Jutta storniert', 'cancelled by the shop'),
    withdrawn: l('widerrufen', 'withdrawn'),
  } satisfies Labels<E.OrderCancelReason>,
  DELIVERED_SOURCES: {
    manual: l('von Hand'),
    auto: l('automatisch'),
  } satisfies Labels<E.DeliveredSource>,
  ORDER_ITEM_STATUSES: {
    active: l('aktiv', 'active'),
    withdrawn: l('widerrufen', 'withdrawn'),
    returned: l('zurückgeschickt', 'returned'),
    refunded: l('erstattet', 'refunded'),
  } satisfies Labels<E.OrderItemStatus>,
  CARRIERS: {
    dhl: l('DHL', 'DHL'),
    deutsche_post: l('Deutsche Post', 'Deutsche Post'),
    other: l('Sonstige', 'Other'),
  } satisfies Labels<E.Carrier>,
  PACKAGING_MATERIALS: {
    paper_cardboard: l('Papier/Pappe/Karton'),
    plastic: l('Kunststoff'),
    other: l('Sonstiges'),
  } satisfies Labels<E.PackagingMaterial>,
  REFUND_REASONS: {
    withdrawal: l('Widerruf', 'withdrawal'),
    goodwill: l('Kulanz', 'goodwill'),
    complaint: l('Reklamation', 'complaint'),
    breakage: l('vor dem Versand beschädigt', 'damaged before shipping'),
    admin_cancellation: l('Stornierung durch Jutta', 'cancelled by the shop'),
    item_unavailable: l('Stück nicht mehr verfügbar', 'item no longer available'),
    dispute: l('Zahlungsanfechtung', 'payment dispute'),
    correction: l('Berichtigung (neue Rechnung)', 'correction (new invoice)'),
  } satisfies Labels<E.RefundReason>,
  REFUND_STATUSES: {
    pending: l('läuft'),
    succeeded: l('erfolgreich'),
    failed: l('gescheitert'),
  } satisfies Labels<E.RefundStatus>,
  DISPUTE_STATUSES: {
    none: l('keine'),
    open: l('offen'),
    won: l('gewonnen'),
    lost: l('verloren'),
  } satisfies Labels<E.DisputeStatus>,
  ATTENTION_REASONS: {
    oversold: l('Stück doppelt bezahlt'),
    dispute_open: l('Zahlung angefochten'),
    refund_failed: l('Erstattung gescheitert'),
    webhook_error: l('Fehler bei der Zahlungsmeldung'),
    payment_amount_mismatch: l('Betrag stimmt nicht'),
    conformity_revoked: l('Konformitätserklärung widerrufen'),
    manual: l('von Hand markiert'),
  } satisfies Labels<E.AttentionReason>,
  COUNTRY_CODES: COUNTRY_LABELS,
  TAX_MODES: {
    kleinunternehmer: l('Kleinunternehmerin (§ 19 UStG)'),
    regelbesteuert: l('Regelbesteuerung'),
  } satisfies Labels<E.TaxMode>,
  INVOICE_TYPES: {
    invoice: l('Rechnung', 'Invoice'),
    credit_note: l('Gutschrift', 'Credit note'),
  } satisfies Labels<E.InvoiceType>,
  INVOICE_SERIES: {
    RE: l('RE (Rechnungen)'),
    GS: l('GS (Gutschriften)'),
    'BSP-RE': l('BSP-RE (Beispiel-Rechnungen)'),
    'BSP-GS': l('BSP-GS (Beispiel-Gutschriften)'),
  } satisfies Labels<E.InvoiceSeries>,
  INVOICE_STATUSES: {
    pending_pdf: l('PDF wird erzeugt'),
    issued: l('ausgestellt'),
  } satisfies Labels<E.InvoiceStatus>,
  REVENUE_SOURCES: {
    tattoo: l('Tattoo'),
    flohmarkt: l('Flohmarkt'),
    auftragsarbeiten: l('Auftragsarbeiten'),
    sonstiges: l('Sonstiges'),
  } satisfies Labels<E.RevenueSource>,
  REVENUE_GUARD_STAGES: {
    U0: l('U0 – Vorjahr über 25.000 € (keine Kleinunternehmerregelung)'),
    U1: l('U1 – 20.000 € erreicht'),
    U2: l('U2 – 25.000 € überschritten'),
    U3: l('U3 – 80.000 € erreicht'),
    U3a: l('U3a – 90.000 € erreicht'),
    U4: l('U4 – 95.000 € erreicht'),
    U5: l('U5 – 100.000 € überschritten'),
  } satisfies Labels<E.RevenueGuardStage>,
  INVOICE_RETENTION_YEARS: {
    8: l('8 Jahre'),
    10: l('10 Jahre'),
  } satisfies Labels<E.InvoiceRetentionYears>,
  LEGAL_TEXT_TYPES: {
    impressum: l('Impressum', 'Legal notice'),
    datenschutz: l('Datenschutzerklärung', 'Privacy policy'),
    agb: l('AGB', 'Terms and conditions'),
    widerrufsbelehrung: l('Widerrufsbelehrung', 'Right of withdrawal'),
    widerrufsformular: l('Muster-Widerrufsformular', 'Model withdrawal form'),
    'versand-zahlung': l('Versand & Zahlung', 'Shipping & payment'),
  } satisfies Labels<E.LegalTextType>,
  LEGAL_TEXT_STATUSES: {
    draft: l('Entwurf'),
    scheduled: l('geplant'),
    active: l('veröffentlicht'),
    superseded: l('ersetzt'),
  } satisfies Labels<E.LegalTextStatus>,
  LEGAL_TEXT_SOURCES: {
    manual: l('von Hand eingefügt'),
    itrk_lti: l('IT-Recht Kanzlei (Schnittstelle)'),
  } satisfies Labels<E.LegalTextSource>,
  LEGAL_TEXT_ORIGINS: {
    placeholder: l('Platzhalter'),
    draft: l('Arbeitsfassung'),
    lawyer: l('Kanzlei'),
  } satisfies Labels<E.LegalTextOrigin>,
  LEGAL_SNIPPET_KEYS: SNIPPET_LABELS,
  WITHDRAWAL_STATUSES: {
    received: l('eingegangen', 'received'),
    goods_returned: l('Ware zurück', 'goods returned'),
    partially_refunded: l('teilweise erstattet', 'partially refunded'),
    refunded: l('erstattet', 'refunded'),
    rejected: l('abgelehnt', 'rejected'),
    closed: l('abgeschlossen', 'closed'),
  } satisfies Labels<E.WithdrawalStatus>,
  WITHDRAWAL_MATCH_STATUSES: {
    auto_matched: l('automatisch zugeordnet'),
    needs_manual_match: l('Zuordnung nötig'),
    manually_matched: l('von Hand zugeordnet'),
    no_order: l('keine Bestellung'),
  } satisfies Labels<E.WithdrawalMatchStatus>,
  WITHDRAWAL_CHANNELS: {
    online_form: l('Widerrufsfunktion'),
    email: l('E-Mail'),
    letter: l('Brief'),
    other: l('Sonstiges'),
  } satisfies Labels<E.WithdrawalChannel>,
  WITHDRAWAL_CLOSE_REASONS: {
    unpaid_order_cancelled: l('unbezahlte Bestellung storniert'),
    duplicate: l('doppelt'),
    retracted: l('zurückgenommen'),
    other: l('Sonstiges'),
  } satisfies Labels<E.WithdrawalCloseReason>,
  COMPLAINT_KINDS: {
    transport_damage: l('Transportschaden', 'transport damage'),
    defect: l('Mangel', 'defect'),
  } satisfies Labels<E.ComplaintKind>,
  COMPLAINT_REMEDIES: {
    repair: l('Reparatur', 'repair'),
    replacement: l('Ersatz', 'replacement'),
    refund: l('Erstattung', 'refund'),
    price_reduction: l('Minderung', 'price reduction'),
    none: l('keine', 'none'),
  } satisfies Labels<E.ComplaintRemedy>,
  COMPLAINT_STATUSES: {
    open: l('offen'),
    waiting_customer: l('wartet auf Kund:in'),
    resolved: l('erledigt'),
    rejected: l('abgelehnt'),
  } satisfies Labels<E.ComplaintStatus>,
  CONFORMITY_STATUSES: {
    active: l('gültig', 'valid'),
    revoked: l('widerrufen', 'revoked'),
  } satisfies Labels<E.ConformityStatus>,
  CONSENT_PURPOSES: {
    carrier_email_forwarding: l('E-Mail an DHL weitergeben', 'Share e-mail with DHL'),
    deviation_agreement: l('Abweichungen vereinbart', 'Deviations agreed'),
    inquiry_privacy_notice: l('Datenschutzhinweis Anfrage', 'Inquiry privacy notice'),
  } satisfies Labels<E.ConsentPurpose>,
  PRIVACY_REQUEST_TYPES: {
    access: l('Auskunft'),
    rectification: l('Berichtigung'),
    erasure: l('Löschung'),
    restriction: l('Einschränkung'),
    portability: l('Datenübertragbarkeit'),
    objection: l('Widerspruch'),
    consent_withdrawal: l('Widerruf einer Einwilligung'),
  } satisfies Labels<E.PrivacyRequestType>,
  PRIVACY_REQUEST_STATUSES: {
    received: l('eingegangen'),
    identity_check: l('Identität prüfen'),
    in_progress: l('in Bearbeitung'),
    answered: l('beantwortet'),
    rejected: l('abgelehnt'),
  } satisfies Labels<E.PrivacyRequestStatus>,
  PRIVACY_REQUEST_CHANNELS: {
    email: l('E-Mail'),
    letter: l('Brief'),
    instagram_dm: l('Instagram-Nachricht'),
    oral: l('mündlich'),
    withdrawal_form: l('Widerrufsformular'),
    other: l('Sonstiges'),
  } satisfies Labels<E.PrivacyRequestChannel>,
  IDENTITY_CHECK_METHODS: {
    stored_email: l('gespeicherte E-Mail-Adresse'),
    control_data: l('Kontrolldaten (z. B. Bestellnummer)'),
    other: l('Sonstiges'),
  } satisfies Labels<E.IdentityCheckMethod>,
  DELETION_ACTIONS: {
    deleted: l('gelöscht'),
    anonymized: l('anonymisiert'),
    restricted: l('eingeschränkt'),
    files_deleted: l('Dateien gelöscht'),
  } satisfies Labels<E.DeletionAction>,
  DELETION_TRIGGERS: {
    job: l('automatische Frist'),
    privacy_request: l('Datenschutz-Anfrage'),
    admin: l('von Hand'),
    consent_withdrawn: l('Einwilligung widerrufen'),
  } satisfies Labels<E.DeletionTrigger>,
  FLASH_STATUSES: {
    available: l('verfügbar', 'available'),
    claimed: l('vergeben', 'taken'),
  } satisfies Labels<E.FlashStatus>,
  TATTOO_PHOTO_KINDS: {
    fresh: l('frisch', 'fresh'),
    healed: l('verheilt', 'healed'),
  } satisfies Labels<E.TattooPhotoKind>,
  CONSENT_SCOPES: {
    tattoo_only: l('nur das Tattoo'),
    with_face: l('mit Gesicht'),
  } satisfies Labels<E.ConsentScope>,
  INQUIRY_STATUSES: {
    new: l('neu'),
    in_progress: l('in Bearbeitung'),
    offer_sent: l('Angebot geschickt'),
    accepted: l('angenommen'),
    declined: l('abgelehnt'),
    completed: l('fertig'),
    closed: l('geschlossen'),
  } satisfies Labels<E.InquiryStatus>,
  INQUIRY_OBJECT_TYPES: {
    cap: l('Cap', 'Cap'),
    shirt: l('Shirt', 'Shirt'),
    textil_sonstiges: l('anderes Textil', 'Other textile'),
    teller: l('Teller', 'Plate'),
    schale: l('Schale', 'Bowl'),
    tasse: l('Tasse', 'Cup'),
    fliese: l('Fliese', 'Tile'),
    zeichnung: l('Zeichnung', 'Drawing'),
    schmuck: l('Schmuck', 'Jewellery'),
    sonstiges: l('Sonstiges', 'Other'),
  } satisfies Labels<E.InquiryObjectType>,
  MEDIA_SOURCES: {
    upload: l('hochgeladen'),
    instagram_seed: l('Instagram (Beispiel)'),
    instagram_export: l('Instagram-Export'),
    placeholder: l('Platzhalter'),
    generated: l('erzeugt'),
  } satisfies Labels<E.MediaSource>,
  SHOWS_PERSON: {
    none: l('keine Person'),
    jutta: l('Jutta'),
    customer: l('Kund:in'),
  } satisfies Labels<E.ShowsPerson>,
  DOCUMENT_KINDS: {
    legal_text_pdf: l('Rechtstext (PDF)', 'Legal text (PDF)'),
    conformity_declaration: l('Konformitätserklärung', 'Declaration of conformity'),
    aftercare_pdf: l('Pflegeanleitung (PDF)', 'Aftercare (PDF)'),
    other: l('Sonstiges', 'Other'),
  } satisfies Labels<E.DocumentKind>,
  PRIVATE_UPLOAD_PURPOSES: {
    commission_reference: l('Referenzbild Anfrage'),
    packing_photo: l('Packfoto'),
    return_photo: l('Foto Rücksendung'),
    complaint_photo: l('Foto Reklamation'),
    nickel_evidence: l('Nachweis nickelfrei'),
    lab_report: l('Laborbericht'),
    consent_evidence: l('Nachweis Einwilligung'),
    supplier_document: l('Lieferantenunterlage'),
    technical_file: l('Technische Unterlage'),
    invoice_pdf: l('Rechnung (PDF)'),
    credit_note_pdf: l('Gutschrift (PDF)'),
    monthly_export: l('Monatsexport'),
    data_export: l('Datenexport'),
    processor_agreement: l('Auftragsverarbeitungsvertrag'),
  } satisfies Labels<E.PrivateUploadPurpose>,
  PRIVATE_UPLOAD_STATUSES: {
    pending: l('noch nicht zugeordnet'),
    attached: l('zugeordnet'),
  } satisfies Labels<E.PrivateUploadStatus>,
  PAGE_KEYS: {
    home: l('Startseite', 'Home'),
    about: l('Über mich', 'About'),
    contact: l('Kontakt', 'Contact'),
    commissions: l('Auftragsarbeiten', 'Commissions'),
    tattoo: l('Tattoo', 'Tattoo'),
    tattoo_aftercare: l('Tattoo-Pflege', 'Tattoo aftercare'),
    shop: l('Shop', 'Shop'),
    archive: l('Archiv', 'Archive'),
    conformity: l('Konformitätserklärungen', 'Declarations of conformity'),
    withdrawal: l('Vertrag widerrufen', 'Withdraw from contract'),
    order_status: l('Bestellstatus', 'Order status'),
    thanks: l('Danke', 'Thank you'),
    not_found: l('Nicht gefunden', 'Not found'),
  } satisfies Labels<E.PageKey>,
  FAQ_CATEGORIES: {
    tattoo: l('Tattoo', 'Tattoo'),
    aftercare: l('Pflege', 'Aftercare'),
    shop: l('Shop', 'Shop'),
    shipping: l('Versand', 'Shipping'),
    commissions: l('Auftragsarbeiten', 'Commissions'),
    general: l('Allgemein', 'General'),
  } satisfies Labels<E.FaqCategory>,
  COCO_POSES: {
    run: l('rennt', 'running'),
    sniff: l('schnüffelt', 'sniffing'),
    sit: l('sitzt', 'sitting'),
    sleep: l('schläft', 'sleeping'),
    jump: l('springt', 'jumping'),
    head_tilt: l('legt den Kopf schief', 'head tilt'),
  } satisfies Labels<E.CocoPose>,
  INTERNAL_LINK_TARGETS: {
    home: l('Startseite', 'Home'),
    shop: l('Shop', 'Shop'),
    archive: l('Archiv', 'Archive'),
    category: l('Kategorie', 'Category'),
    tattoo: l('Tattoo', 'Tattoo'),
    tattoo_aftercare: l('Tattoo-Pflege', 'Tattoo aftercare'),
    about: l('Über mich', 'About'),
    commissions: l('Auftragsarbeiten', 'Commissions'),
    contact: l('Kontakt', 'Contact'),
    conformity: l('Konformitätserklärungen', 'Declarations of conformity'),
    instagram: l('Instagram', 'Instagram'),
    email: l('E-Mail', 'E-mail'),
  } satisfies Labels<E.InternalLinkTarget>,
  ACTOR_TYPES: {
    admin: l('Jutta'),
    system: l('System'),
    webhook: l('Zahlungsdienst'),
    job: l('Automatik'),
    customer: l('Kund:in'),
    seed: l('Beispieldaten'),
  } satisfies Labels<E.ActorType>,
  AUDIT_ACTIONS: AUDIT_LABELS,
  EMAIL_TEMPLATES: EMAIL_TEMPLATE_LABELS,
  EMAIL_STATUSES: {
    queued: l('wartet'),
    sent: l('gesendet'),
    failed: l('gescheitert'),
    suppressed: l('unterdrückt'),
  } satisfies Labels<E.EmailStatus>,
  EMAIL_TRANSPORTS: {
    file: l('Datei'),
    smtp: l('SMTP'),
    memory: l('Speicher (Test)'),
    log: l('Protokoll'),
  } satisfies Labels<E.EmailTransport>,
  WEBHOOK_PROVIDERS: {
    stripe: l('Stripe'),
    mock: l('Test-Zahlung (Mock)'),
  } satisfies Labels<E.WebhookProvider>,
  WEBHOOK_EVENT_STATUSES: {
    processing: l('in Bearbeitung'),
    processed: l('verarbeitet'),
    failed: l('gescheitert'),
    ignored: l('ignoriert'),
  } satisfies Labels<E.WebhookEventStatus>,
} as const

export type EnumName = keyof typeof ENUM_LABELS

/**
 * Anzeigename der einen Versandoption einer Kasse (KONZEPT §4.7 „DHL Paket (Keramik)“ bzw. „Abholung in Berlin“):
 * Stripe `shipping_options`, Kassen-Übersicht, Belege. Schlüssel = Versandklasse bzw. `pickup` (P4.2).
 */
export const SHIPPING_OPTION_LABELS: Record<
  Exclude<E.ShippingClass, 'nur_abholung'> | 'pickup',
  { de: string; en: string }
> = {
  brief: { de: 'Deutsche Post (Brief)', en: 'Deutsche Post (letter)' },
  paket_klein: { de: 'DHL Paket (klein)', en: 'DHL parcel (small)' },
  keramik: { de: 'DHL Paket (Keramik)', en: 'DHL parcel (ceramics)' },
  pickup: { de: 'Abholung in Berlin', en: 'Pickup in Berlin' },
}

/** Enums, deren Werte Besucher:innen sehen – brauchen ein EN-Label. */
export const PUBLIC_ENUMS: readonly EnumName[] = [
  'LOCALES',
  'PRODUCT_CATEGORIES',
  'PRODUCT_STATUSES',
  'SHIPPING_CLASSES',
  'FOOD_CONTACT',
  'TEXTILE_CONDITIONS',
  'FIBER_COMPONENTS',
  'TEXTILE_FIBERS',
  'CHECKOUT_PAYMENT_CHOICES',
  'FULFILLMENT_METHODS',
  'PAYMENT_METHODS',
  'ORDER_STATUSES',
  'ORDER_ITEM_STATUSES',
  'CARRIERS',
  'COUNTRY_CODES',
  'INVOICE_TYPES',
  'LEGAL_TEXT_TYPES',
  'WITHDRAWAL_STATUSES',
  'COMPLAINT_KINDS',
  'CONSENT_PURPOSES',
  'FLASH_STATUSES',
  'TATTOO_PHOTO_KINDS',
  'INQUIRY_OBJECT_TYPES',
  'DOCUMENT_KINDS',
  'PAGE_KEYS',
  'FAQ_CATEGORIES',
  'INTERNAL_LINK_TARGETS',
]

/** Payload-`options` für ein Select-Feld (DATENMODELL §4: Werte nur aus enums.ts). */
export function enumOptions<T extends string>(values: readonly T[], labels: Record<T, EnumLabel>) {
  return values.map((value) => ({ value, label: labels[value].de }))
}

/** Anzeige-Label für Besucher:innen. */
export function publicLabel(label: EnumLabel, locale: 'de' | 'en'): string {
  if (locale === 'en') return label.customerEn ?? label.en ?? label.de
  return label.customerDe ?? label.de
}
