/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    documents: Document;
    'private-uploads': PrivateUpload;
    'audit-log': AuditLog;
    'email-log': EmailLog;
    'consent-log': ConsentLog;
    'webhook-events': WebhookEvent;
    'deletion-log': DeletionLog;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'private-uploads': PrivateUploadsSelect<false> | PrivateUploadsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'email-log': EmailLogSelect<false> | EmailLogSelect<true>;
    'consent-log': ConsentLogSelect<false> | ConsentLogSelect<true>;
    'webhook-events': WebhookEventsSelect<false> | WebhookEventsSelect<true>;
    'deletion-log': DeletionLogSelect<false> | DeletionLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('de' | 'en') | ('de' | 'en')[];
  globals: {
    settings: Setting;
    'site-texts': SiteText;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'site-texts': SiteTextsSelect<false> | SiteTextsSelect<true>;
  };
  locale: 'de' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      sendEmail: TaskSendEmail;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Dein Zugang zur Verwaltung. Es gibt genau ein Konto.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin';
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Bilder für Shop, Seiten und Galerie. Große Fotos werden vor dem Hochladen verkleinert; Standortdaten werden entfernt.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Was ist zu sehen? Objekt, Motiv, Farbe.
   */
  alt?: string | null;
  caption?: string | null;
  /**
   * „Kund:in“ = Haut oder Tattoo einer Kundin/eines Kunden (nie öffentlich ohne Einwilligung).
   */
  showsPerson: 'none' | 'jutta' | 'customer';
  restricted?: boolean | null;
  source: 'upload' | 'instagram_seed' | 'instagram_export' | 'placeholder' | 'generated';
  sourceRef?: string | null;
  /**
   * Wirkt ab P9 (einheitlicher Bildlook).
   */
  enhance: 'auto' | 'off';
  derivativesVersion?: number | null;
  placeholderDataUrl?: string | null;
  dominantColor?: string | null;
  seed?: boolean | null;
  seedKey?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    detail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    zoom?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Öffentlich abrufbare PDFs (z. B. Konformitätserklärungen, Pflegehinweise). Nur PDF, höchstens 20 MB.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  kind: 'legal_text_pdf' | 'conformity_declaration' | 'aftercare_pdf' | 'other';
  language?: ('de' | 'en') | null;
  sha256?: string | null;
  seed?: boolean | null;
  seedKey?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Nicht öffentliche Dateien (Referenzbilder, Packfotos, Nachweise, Belege). Nur angemeldet abrufbar; Standortdaten werden aus Fotos entfernt. Höchstens 10 MB je Datei.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "private-uploads".
 */
export interface PrivateUpload {
  id: number;
  /**
   * Nach dem Hochladen nicht mehr änderbar – bestimmt die Löschfrist.
   */
  purpose:
    | 'commission_reference'
    | 'packing_photo'
    | 'return_photo'
    | 'complaint_photo'
    | 'nickel_evidence'
    | 'lab_report'
    | 'consent_evidence'
    | 'supplier_document'
    | 'technical_file'
    | 'invoice_pdf'
    | 'credit_note_pdf'
    | 'monthly_export'
    | 'data_export'
    | 'processor_agreement';
  status: 'pending' | 'attached';
  /**
   * Wird automatisch berechnet. Du kannst die Frist nur verkürzen.
   */
  deleteAfter?: string | null;
  /**
   * Belege: vorher ist Löschen nicht möglich.
   */
  retainUntil?: string | null;
  sha256?: string | null;
  /**
   * Nur bei Nachweisen und Unterlagen; bei technischen Unterlagen Pflicht.
   */
  complianceCategory?: ('keramik' | 'textil' | 'cap' | 'zeichnung' | 'schmuck' | 'sonstiges') | null;
  /**
   * z. B. „Datenblatt 2026-03“
   */
  documentVersion?: string | null;
  documentDate?: string | null;
  note?: string | null;
  seed?: boolean | null;
  seedKey?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Wer hat wann was geändert. Nur lesen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  action:
    | 'product_created'
    | 'product_published'
    | 'product_status_changed'
    | 'product_price_changed'
    | 'product_offline_sold'
    | 'product_adopted'
    | 'product_deleted'
    | 'reservation_conflict'
    | 'order_created'
    | 'order_status_changed'
    | 'order_address_changed'
    | 'order_status_link_rotated'
    | 'order_refund_created'
    | 'order_refund_failed'
    | 'packing_photo_skipped'
    | 'carrier_consent_withdrawn'
    | 'complaint_changed'
    | 'invoice_issued'
    | 'credit_note_issued'
    | 'withdrawal_received'
    | 'withdrawal_matched'
    | 'withdrawal_status_changed'
    | 'legal_text_activated'
    | 'legal_text_superseded'
    | 'legal_snippet_activated'
    | 'legal_snippet_superseded'
    | 'legal_review_confirmed'
    | 'settings_changed'
    | 'tax_mode_changed'
    | 'gallery_published'
    | 'gallery_consent_withdrawn'
    | 'inquiry_status_changed'
    | 'inquiry_deleted'
    | 'private_upload_deleted'
    | 'order_anonymized'
    | 'data_exported'
    | 'legal_hold_changed'
    | 'processing_restricted'
    | 'privacy_request_changed'
    | 'retention_setting_changed'
    | 'seed_imported'
    | 'seed_removed'
    | 'login_succeeded'
    | 'password_reset_requested';
  actorType: 'admin' | 'system' | 'webhook' | 'job' | 'customer' | 'seed';
  actorUser?: (number | null) | User;
  entityCollection: string;
  entityId: string;
  summary: string;
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  retainUntil: string;
  seed?: boolean | null;
  seedKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Welche Mail wann verschickt wurde (ohne Inhalt). Nur lesen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-log".
 */
export interface EmailLog {
  id: number;
  template:
    | 'order_confirmation'
    | 'prepayment_instructions'
    | 'prepayment_reminder'
    | 'prepayment_cancelled'
    | 'prepayment_received'
    | 'order_shipped'
    | 'pickup_ready'
    | 'withdrawal_receipt'
    | 'refund_confirmation'
    | 'oversold_apology'
    | 'inquiry_receipt'
    | 'complaint_repair_choice'
    | 'dispute_vsbg'
    | 'privacy_access_response'
    | 'privacy_erasure_response'
    | 'consent_withdrawal_confirmation'
    | 'admin_order_placed'
    | 'admin_prepayment_cancelled'
    | 'admin_withdrawal_received'
    | 'admin_inquiry_received'
    | 'admin_oversold'
    | 'admin_dispute_opened'
    | 'admin_refund_failed'
    | 'admin_revenue_guard'
    | 'admin_legal_review_due'
    | 'admin_monthly_close'
    | 'admin_alert'
    | 'admin_withdrawal_deadline'
    | 'admin_password_reset'
    | 'admin_privacy_request_due'
    | 'admin_legal_hold_review'
    | 'admin_compliance_docs_review';
  to: string;
  locale: 'de' | 'en';
  subject: string;
  status: 'queued' | 'sent' | 'failed' | 'suppressed';
  transport?: ('file' | 'smtp' | 'memory' | 'log') | null;
  messageId?: string | null;
  smtpResponse?: string | null;
  sentAt?: string | null;
  attempts?: number | null;
  lastError?: string | null;
  attachments?:
    | {
        filename: string;
        sha256: string;
        sizeBytes: number;
        id?: string | null;
      }[]
    | null;
  templateVersion?: string | null;
  bodySha256?: string | null;
  retainUntil: string;
  seed?: boolean | null;
  seedKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Nachweis von Einwilligungen und Vereinbarungen. Nur lesen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-log".
 */
export interface ConsentLog {
  id: number;
  purpose: 'carrier_email_forwarding' | 'deviation_agreement' | 'inquiry_privacy_notice';
  granted: boolean;
  textSnapshot: string;
  textSha256: string;
  snippetKey?: string | null;
  snippetVersion?: string | null;
  locale: 'de' | 'en';
  email: string;
  withdrawnAt?: string | null;
  retainUntil: string;
  seed?: boolean | null;
  seedKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Eingegangene Zahlungs-Ereignisse (ohne Personendaten). Nur lesen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-events".
 */
export interface WebhookEvent {
  id: number;
  provider: 'stripe' | 'mock';
  eventId: string;
  type: string;
  livemode: boolean;
  status: 'processing' | 'processed' | 'failed' | 'ignored';
  attempts: number;
  receivedAt?: string | null;
  processedAt?: string | null;
  lastError?: string | null;
  payloadSha256?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Nachweis aller Löschungen (ohne Inhalte, Namen oder E-Mail-Adressen). Nur lesen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deletion-log".
 */
export interface DeletionLog {
  id: number;
  entityCollection: string;
  entityId: string;
  ruleId: string;
  action: 'deleted' | 'anonymized' | 'restricted' | 'files_deleted';
  trigger: 'job' | 'privacy_request' | 'admin' | 'consent_withdrawn';
  taskSlug?: string | null;
  privacyRequestRef?: string | null;
  storageObjectsCount: number;
  executedAt: string;
  retainUntil: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'sendEmail';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'sendEmail') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'private-uploads';
        value: number | PrivateUpload;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'email-log';
        value: number | EmailLog;
      } | null)
    | ({
        relationTo: 'consent-log';
        value: number | ConsentLog;
      } | null)
    | ({
        relationTo: 'webhook-events';
        value: number | WebhookEvent;
      } | null)
    | ({
        relationTo: 'deletion-log';
        value: number | DeletionLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  showsPerson?: T;
  restricted?: T;
  source?: T;
  sourceRef?: T;
  enhance?: T;
  derivativesVersion?: T;
  placeholderDataUrl?: T;
  dominantColor?: T;
  seed?: T;
  seedKey?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        detail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        zoom?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  language?: T;
  sha256?: T;
  seed?: T;
  seedKey?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "private-uploads_select".
 */
export interface PrivateUploadsSelect<T extends boolean = true> {
  purpose?: T;
  status?: T;
  deleteAfter?: T;
  retainUntil?: T;
  sha256?: T;
  complianceCategory?: T;
  documentVersion?: T;
  documentDate?: T;
  note?: T;
  seed?: T;
  seedKey?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  action?: T;
  actorType?: T;
  actorUser?: T;
  entityCollection?: T;
  entityId?: T;
  summary?: T;
  changes?: T;
  retainUntil?: T;
  seed?: T;
  seedKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-log_select".
 */
export interface EmailLogSelect<T extends boolean = true> {
  template?: T;
  to?: T;
  locale?: T;
  subject?: T;
  status?: T;
  transport?: T;
  messageId?: T;
  smtpResponse?: T;
  sentAt?: T;
  attempts?: T;
  lastError?: T;
  attachments?:
    | T
    | {
        filename?: T;
        sha256?: T;
        sizeBytes?: T;
        id?: T;
      };
  templateVersion?: T;
  bodySha256?: T;
  retainUntil?: T;
  seed?: T;
  seedKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-log_select".
 */
export interface ConsentLogSelect<T extends boolean = true> {
  purpose?: T;
  granted?: T;
  textSnapshot?: T;
  textSha256?: T;
  snippetKey?: T;
  snippetVersion?: T;
  locale?: T;
  email?: T;
  withdrawnAt?: T;
  retainUntil?: T;
  seed?: T;
  seedKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-events_select".
 */
export interface WebhookEventsSelect<T extends boolean = true> {
  provider?: T;
  eventId?: T;
  type?: T;
  livemode?: T;
  status?: T;
  attempts?: T;
  receivedAt?: T;
  processedAt?: T;
  lastError?: T;
  payloadSha256?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deletion-log_select".
 */
export interface DeletionLogSelect<T extends boolean = true> {
  entityCollection?: T;
  entityId?: T;
  ruleId?: T;
  action?: T;
  trigger?: T;
  taskSlug?: T;
  privacyRequestRef?: T;
  storageObjectsCount?: T;
  executedAt?: T;
  retainUntil?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  shop?: {
    /**
     * Aus: „In den Korb“ und „Zur Kasse“ sind gesperrt; laufende Kassen und Zahlungen werden normal abgeschlossen.
     */
    isOpen?: boolean | null;
    closedMessage?: string | null;
    maxItemsPerCheckout?: number | null;
  };
  business: {
    legalName: string;
    tradeName?: string | null;
    street: string;
    postalCode?: string | null;
    city: string;
    country?:
      | (
          | 'DE'
          | 'AT'
          | 'BE'
          | 'BG'
          | 'CY'
          | 'CZ'
          | 'DK'
          | 'EE'
          | 'ES'
          | 'FI'
          | 'FR'
          | 'GR'
          | 'HR'
          | 'HU'
          | 'IE'
          | 'IT'
          | 'LT'
          | 'LU'
          | 'LV'
          | 'MT'
          | 'NL'
          | 'PL'
          | 'PT'
          | 'RO'
          | 'SE'
          | 'SI'
          | 'SK'
          | 'CH'
        )
      | null;
    email: string;
    /**
     * Pflicht zum Start (Impressum, Widerrufsbelehrung, Bestellbestätigung).
     */
    phone?: string | null;
    vatId?: string | null;
    economicId?: string | null;
    /**
     * Nur für Rechnungen – nie öffentlich.
     */
    taxNumber?: string | null;
    /**
     * Leer = Geschäftsadresse.
     */
    returnAddress?: string | null;
    lucidNumber?: string | null;
    packagingScheme?: {
      name?: string | null;
      contractFrom?: string | null;
    };
  };
  social?: {
    instagramHandle?: string | null;
    contactEmail?: string | null;
  };
  tax?: {
    /**
     * Geltend ist der letzte Eintrag mit „gültig ab“ ≤ heute. Neue Einträge nur mit Begründung und nach Rücksprache mit der Steuerberatung.
     */
    modes?:
      | {
          mode: 'kleinunternehmer' | 'regelbesteuert';
          validFrom: string;
          reason?: string | null;
          confirmedWithTaxAdvisor?: boolean | null;
          id?: string | null;
        }[]
      | null;
    confirmedAt?: string | null;
    standardRate?: number | null;
    reducedRate?: number | null;
  };
  revenueGuard?: {
    previousYearLimitCents?: number | null;
    currentYearLimitCents?: number | null;
    stageThresholdsCents?: {
      u1?: number | null;
      u3?: number | null;
      u3a?: number | null;
      u4?: number | null;
    };
    manualYearTotals?:
      | {
          year: number;
          amountCents: number;
          note?: string | null;
          id?: string | null;
        }[]
      | null;
    lastNotified?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  retention?: {
    /**
     * Achtung: nur nach Antwort von Kanzlei/Steuerberatung (K-33) umstellen. Wirkt nur auf neue Belege.
     */
    invoiceYears?: ('8' | '10') | null;
  };
  export?: {
    datev?: {
      consultantNumber?: string | null;
      clientNumber?: string | null;
      fiscalYearStart?: string | null;
      revenueAccount?: string | null;
      stripeTransitAccount?: string | null;
      bankAccount?: string | null;
      feeAccount?: string | null;
    };
  };
  costs?: {
    budgetCents?: number | null;
    warningThresholdCents?: number | null;
    monthlyEntries?:
      | {
          month: string;
          amountCents: number;
          note?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  shipping?: {
    /**
     * Start nur Deutschland. Andere Länder erst nach der EU-Checkliste und dem Häkchen „EU-Versand geprüft“.
     */
    enabledCountries?:
      | (
          | 'DE'
          | 'AT'
          | 'BE'
          | 'BG'
          | 'CY'
          | 'CZ'
          | 'DK'
          | 'EE'
          | 'ES'
          | 'FI'
          | 'FR'
          | 'GR'
          | 'HR'
          | 'HU'
          | 'IE'
          | 'IT'
          | 'LT'
          | 'LU'
          | 'LV'
          | 'MT'
          | 'NL'
          | 'PL'
          | 'PT'
          | 'RO'
          | 'SE'
          | 'SI'
          | 'SK'
          | 'CH'
        )[]
      | null;
    euShippingAcknowledged?: boolean | null;
    euShippingAcknowledgedAt?: string | null;
    euChecklist?: {
      authorisedRepresentativeNamed?: boolean | null;
      ossThresholdChecked?: boolean | null;
      textileLanguageChecked?: boolean | null;
      ratesMaintained?: boolean | null;
      legalTextsAdapted?: boolean | null;
    };
    pickupEnabled?: boolean | null;
    pickupCity?: string | null;
    rates?:
      | {
          zone: 'DE' | 'EU' | 'CH';
          shippingClass: 'brief' | 'paket_klein' | 'keramik';
          priceCents: number;
          id?: string | null;
        }[]
      | null;
    deliveryTimeText?: string | null;
    insuranceHintThresholdCents?: number | null;
    trackingUrlTemplates?:
      | {
          carrier: 'dhl' | 'deutsche_post' | 'other';
          urlTemplate: string;
          id?: string | null;
        }[]
      | null;
  };
  pickup?: {
    instructions?: string | null;
  };
  /**
   * Gewichte sind Schätzwerte – bitte einmal nachwiegen (Verpackungsmeldung).
   */
  packaging?: {
    templates?:
      | {
          key: string;
          name: string;
          components?:
            | {
                material: 'paper_cardboard' | 'plastic' | 'other';
                grams: number;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    defaultsByShippingClass?:
      | {
          shippingClass: 'brief' | 'paket_klein' | 'keramik';
          templateKey: string;
          id?: string | null;
        }[]
      | null;
  };
  payment?: {
    prepaymentEnabled?: boolean | null;
    accountHolder?: string | null;
    /**
     * Beispiel-IBAN bis zum Start – die Startprüfung meldet sie.
     */
    iban?: string | null;
    bic?: string | null;
    bankName?: string | null;
    reservationMinutes?: number | null;
    prepaymentDays?: number | null;
    prepaymentReminderHours?: number | null;
    stripePaymentMethodConfigurationId?: string | null;
  };
  tattoo?: {
    /**
     * Nur der Bezirk, keine Adresse.
     */
    studioDistrict?: string | null;
    minPriceCents?: number | null;
    customPriceFromCents?: number | null;
    customPriceToCents?: number | null;
    priceNote?: string | null;
  };
  legal?: {
    reviewIntervalDays?: number | null;
    reviews?:
      | {
          type: 'impressum' | 'datenschutz' | 'agb' | 'widerrufsbelehrung' | 'widerrufsformular' | 'versand-zahlung';
          reviewedAt?: string | null;
          lastReminderSentAt?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Achtung: nur nach Antwort der Kanzlei (K-13) einschalten. Aus = Stücke mit sichtbarer Fremdmarke lassen sich nicht veröffentlichen.
     */
    allowVisibleBlankBrands?: boolean | null;
  };
  safetyTemplates?:
    | {
        category: 'keramik' | 'textil' | 'cap' | 'zeichnung' | 'schmuck' | 'sonstiges';
        text: string;
        id?: string | null;
      }[]
    | null;
  careTemplates?:
    | {
        category: 'textil' | 'cap';
        text: string;
        id?: string | null;
      }[]
    | null;
  packingChecklists?:
    | {
        shippingClass: 'brief' | 'paket_klein' | 'keramik' | 'nur_abholung';
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  processorAgreements?:
    | {
        serviceId: string;
        signedAt?: string | null;
        documentVersion?: string | null;
        url?: string | null;
        file?: (number | null) | PrivateUpload;
        id?: string | null;
      }[]
    | null;
  analytics?: {
    enabled?: boolean | null;
    confirmedAt?: string | null;
    note?: string | null;
  };
  adminNotificationEmail?: string | null;
  seed?: {
    exampleDataPresent?: boolean | null;
    importedAt?: string | null;
    removedAt?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-texts".
 */
export interface SiteText {
  id: number;
  navigation?: {
    mainLinks?:
      | {
          target:
            | 'home'
            | 'shop'
            | 'archive'
            | 'category'
            | 'tattoo'
            | 'tattoo_aftercare'
            | 'about'
            | 'commissions'
            | 'contact'
            | 'conformity'
            | 'instagram'
            | 'email';
          category?: ('keramik' | 'textil' | 'cap' | 'zeichnung' | 'schmuck' | 'sonstiges') | null;
          label: string;
          id?: string | null;
        }[]
      | null;
    menuLinks?:
      | {
          target:
            | 'home'
            | 'shop'
            | 'archive'
            | 'category'
            | 'tattoo'
            | 'tattoo_aftercare'
            | 'about'
            | 'commissions'
            | 'contact'
            | 'conformity'
            | 'instagram'
            | 'email';
          category?: ('keramik' | 'textil' | 'cap' | 'zeichnung' | 'schmuck' | 'sonstiges') | null;
          label: string;
          id?: string | null;
        }[]
      | null;
    menuTagline?: string | null;
  };
  footer?: {
    tagline?: string | null;
    instagramLabel?: string | null;
  };
  shop?: {
    filterAll?: string | null;
    filterAvailableOnly?: string | null;
    soldStamp?: string | null;
    reservedLabel?: string | null;
    reservedPrepaymentLabel?: string | null;
    uniqueHint?: string | null;
    emptyCategory?: string | null;
    archiveIntro?: string | null;
  };
  product?: {
    addToCart?: string | null;
    shippingLinkLabel?: string | null;
    manufacturerHeading?: string | null;
    deviationHeading?: string | null;
    fiberHeading?: string | null;
    labelMissingHint?: string | null;
  };
  cart?: {
    empty?: string | null;
    countdown?: string | null;
    reservationExpired?: string | null;
    pickupOption?: string | null;
    shippingOption?: string | null;
  };
  checkout?: {
    intro?: string | null;
    changeLink?: string | null;
  };
  thanks?: {
    heading?: string | null;
    intro?: string | null;
  };
  orderStatus?: {
    intro?: string | null;
    linkInvalid?: string | null;
  };
  withdrawal?: {
    intro?: string | null;
    done?: string | null;
  };
  notFound?: {
    heading?: string | null;
    intro?: string | null;
  };
  errors?: {
    generic?: string | null;
    shopClosed?: string | null;
    alreadyReserved?: string | null;
  };
  emails?: {
    /**
     * Steht unter jeder Mail an Kund:innen.
     */
    signature?: string | null;
    inquiryResponseTime?: string | null;
    /**
     * Leer bzw. ohne Zeile = Standardtext der Vorlage.
     */
    templates?:
      | {
          template:
            | 'order_confirmation'
            | 'prepayment_instructions'
            | 'prepayment_reminder'
            | 'prepayment_cancelled'
            | 'prepayment_received'
            | 'order_shipped'
            | 'pickup_ready'
            | 'withdrawal_receipt'
            | 'refund_confirmation'
            | 'oversold_apology'
            | 'inquiry_receipt'
            | 'complaint_repair_choice'
            | 'dispute_vsbg'
            | 'privacy_access_response'
            | 'privacy_erasure_response'
            | 'consent_withdrawal_confirmation'
            | 'admin_order_placed'
            | 'admin_prepayment_cancelled'
            | 'admin_withdrawal_received'
            | 'admin_inquiry_received'
            | 'admin_oversold'
            | 'admin_dispute_opened'
            | 'admin_refund_failed'
            | 'admin_revenue_guard'
            | 'admin_legal_review_due'
            | 'admin_monthly_close'
            | 'admin_alert'
            | 'admin_withdrawal_deadline'
            | 'admin_password_reset'
            | 'admin_privacy_request_due'
            | 'admin_legal_hold_review'
            | 'admin_compliance_docs_review';
          subject?: string | null;
          intro?: string | null;
          outro?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  shop?:
    | T
    | {
        isOpen?: T;
        closedMessage?: T;
        maxItemsPerCheckout?: T;
      };
  business?:
    | T
    | {
        legalName?: T;
        tradeName?: T;
        street?: T;
        postalCode?: T;
        city?: T;
        country?: T;
        email?: T;
        phone?: T;
        vatId?: T;
        economicId?: T;
        taxNumber?: T;
        returnAddress?: T;
        lucidNumber?: T;
        packagingScheme?:
          | T
          | {
              name?: T;
              contractFrom?: T;
            };
      };
  social?:
    | T
    | {
        instagramHandle?: T;
        contactEmail?: T;
      };
  tax?:
    | T
    | {
        modes?:
          | T
          | {
              mode?: T;
              validFrom?: T;
              reason?: T;
              confirmedWithTaxAdvisor?: T;
              id?: T;
            };
        confirmedAt?: T;
        standardRate?: T;
        reducedRate?: T;
      };
  revenueGuard?:
    | T
    | {
        previousYearLimitCents?: T;
        currentYearLimitCents?: T;
        stageThresholdsCents?:
          | T
          | {
              u1?: T;
              u3?: T;
              u3a?: T;
              u4?: T;
            };
        manualYearTotals?:
          | T
          | {
              year?: T;
              amountCents?: T;
              note?: T;
              id?: T;
            };
        lastNotified?: T;
      };
  retention?:
    | T
    | {
        invoiceYears?: T;
      };
  export?:
    | T
    | {
        datev?:
          | T
          | {
              consultantNumber?: T;
              clientNumber?: T;
              fiscalYearStart?: T;
              revenueAccount?: T;
              stripeTransitAccount?: T;
              bankAccount?: T;
              feeAccount?: T;
            };
      };
  costs?:
    | T
    | {
        budgetCents?: T;
        warningThresholdCents?: T;
        monthlyEntries?:
          | T
          | {
              month?: T;
              amountCents?: T;
              note?: T;
              id?: T;
            };
      };
  shipping?:
    | T
    | {
        enabledCountries?: T;
        euShippingAcknowledged?: T;
        euShippingAcknowledgedAt?: T;
        euChecklist?:
          | T
          | {
              authorisedRepresentativeNamed?: T;
              ossThresholdChecked?: T;
              textileLanguageChecked?: T;
              ratesMaintained?: T;
              legalTextsAdapted?: T;
            };
        pickupEnabled?: T;
        pickupCity?: T;
        rates?:
          | T
          | {
              zone?: T;
              shippingClass?: T;
              priceCents?: T;
              id?: T;
            };
        deliveryTimeText?: T;
        insuranceHintThresholdCents?: T;
        trackingUrlTemplates?:
          | T
          | {
              carrier?: T;
              urlTemplate?: T;
              id?: T;
            };
      };
  pickup?:
    | T
    | {
        instructions?: T;
      };
  packaging?:
    | T
    | {
        templates?:
          | T
          | {
              key?: T;
              name?: T;
              components?:
                | T
                | {
                    material?: T;
                    grams?: T;
                    id?: T;
                  };
              id?: T;
            };
        defaultsByShippingClass?:
          | T
          | {
              shippingClass?: T;
              templateKey?: T;
              id?: T;
            };
      };
  payment?:
    | T
    | {
        prepaymentEnabled?: T;
        accountHolder?: T;
        iban?: T;
        bic?: T;
        bankName?: T;
        reservationMinutes?: T;
        prepaymentDays?: T;
        prepaymentReminderHours?: T;
        stripePaymentMethodConfigurationId?: T;
      };
  tattoo?:
    | T
    | {
        studioDistrict?: T;
        minPriceCents?: T;
        customPriceFromCents?: T;
        customPriceToCents?: T;
        priceNote?: T;
      };
  legal?:
    | T
    | {
        reviewIntervalDays?: T;
        reviews?:
          | T
          | {
              type?: T;
              reviewedAt?: T;
              lastReminderSentAt?: T;
              id?: T;
            };
        allowVisibleBlankBrands?: T;
      };
  safetyTemplates?:
    | T
    | {
        category?: T;
        text?: T;
        id?: T;
      };
  careTemplates?:
    | T
    | {
        category?: T;
        text?: T;
        id?: T;
      };
  packingChecklists?:
    | T
    | {
        shippingClass?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  processorAgreements?:
    | T
    | {
        serviceId?: T;
        signedAt?: T;
        documentVersion?: T;
        url?: T;
        file?: T;
        id?: T;
      };
  analytics?:
    | T
    | {
        enabled?: T;
        confirmedAt?: T;
        note?: T;
      };
  adminNotificationEmail?: T;
  seed?:
    | T
    | {
        exampleDataPresent?: T;
        importedAt?: T;
        removedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-texts_select".
 */
export interface SiteTextsSelect<T extends boolean = true> {
  navigation?:
    | T
    | {
        mainLinks?:
          | T
          | {
              target?: T;
              category?: T;
              label?: T;
              id?: T;
            };
        menuLinks?:
          | T
          | {
              target?: T;
              category?: T;
              label?: T;
              id?: T;
            };
        menuTagline?: T;
      };
  footer?:
    | T
    | {
        tagline?: T;
        instagramLabel?: T;
      };
  shop?:
    | T
    | {
        filterAll?: T;
        filterAvailableOnly?: T;
        soldStamp?: T;
        reservedLabel?: T;
        reservedPrepaymentLabel?: T;
        uniqueHint?: T;
        emptyCategory?: T;
        archiveIntro?: T;
      };
  product?:
    | T
    | {
        addToCart?: T;
        shippingLinkLabel?: T;
        manufacturerHeading?: T;
        deviationHeading?: T;
        fiberHeading?: T;
        labelMissingHint?: T;
      };
  cart?:
    | T
    | {
        empty?: T;
        countdown?: T;
        reservationExpired?: T;
        pickupOption?: T;
        shippingOption?: T;
      };
  checkout?:
    | T
    | {
        intro?: T;
        changeLink?: T;
      };
  thanks?:
    | T
    | {
        heading?: T;
        intro?: T;
      };
  orderStatus?:
    | T
    | {
        intro?: T;
        linkInvalid?: T;
      };
  withdrawal?:
    | T
    | {
        intro?: T;
        done?: T;
      };
  notFound?:
    | T
    | {
        heading?: T;
        intro?: T;
      };
  errors?:
    | T
    | {
        generic?: T;
        shopClosed?: T;
        alreadyReserved?: T;
      };
  emails?:
    | T
    | {
        signature?: T;
        inquiryResponseTime?: T;
        templates?:
          | T
          | {
              template?: T;
              subject?: T;
              intro?: T;
              outro?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendEmail".
 */
export interface TaskSendEmail {
  input: {
    emailLogId: number;
  };
  output: {
    status: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}