/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'audit-log': AuditLog;
    'email-log': EmailLog;
    'consent-log': ConsentLog;
    'webhook-events': WebhookEvent;
    'deletion-log': DeletionLog;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'email-log': EmailLogSelect<false> | EmailLogSelect<true>;
    'consent-log': ConsentLogSelect<false> | ConsentLogSelect<true>;
    'webhook-events': WebhookEventsSelect<false> | WebhookEventsSelect<true>;
    'deletion-log': DeletionLogSelect<false> | DeletionLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('de' | 'en') | ('de' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'de' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      sendEmail: TaskSendEmail;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Dein Zugang zur Verwaltung. Es gibt genau ein Konto.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin';
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Bilder für Shop, Seiten und Galerie. Große Fotos werden vor dem Hochladen verkleinert; Standortdaten werden entfernt.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Was ist zu sehen? Objekt, Motiv, Farbe.
   */
  alt?: string | null;
  caption?: string | null;
  /**
   * „Kund:in“ = Haut oder Tattoo einer Kundin/eines Kunden (nie öffentlich ohne Einwilligung).
   */
  showsPerson: 'none' | 'jutta' | 'customer';
  restricted?: boolean | null;
  source: 'upload' | 'instagram_seed' | 'instagram_export' | 'placeholder' | 'generated';
  sourceRef?: string | null;
  /**
   * Wirkt ab P9 (einheitlicher Bildlook).
   */
  enhance: 'auto' | 'off';
  derivativesVersion?: number | null;
  placeholderDataUrl?: string | null;
  dominantColor?: string | null;
  seed?: boolean | null;
  seedKey?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    detail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    zoom?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Wer hat wann was geändert. Nur lesen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  action:
    | 'product_created'
    | 'product_published'
    | 'product_status_changed'
    | 'product_price_changed'
    | 'product_offline_sold'
    | 'product_adopted'
    | 'product_deleted'
    | 'reservation_conflict'
    | 'order_created'
    | 'order_status_changed'
    | 'order_address_changed'
    | 'order_status_link_rotated'
    | 'order_refund_created'
    | 'order_refund_failed'
    | 'packing_photo_skipped'
    | 'carrier_consent_withdrawn'
    | 'complaint_changed'
    | 'invoice_issued'
    | 'credit_note_issued'
    | 'withdrawal_received'
    | 'withdrawal_matched'
    | 'withdrawal_status_changed'
    | 'legal_text_activated'
    | 'legal_text_superseded'
    | 'legal_snippet_activated'
    | 'legal_snippet_superseded'
    | 'legal_review_confirmed'
    | 'settings_changed'
    | 'tax_mode_changed'
    | 'gallery_published'
    | 'gallery_consent_withdrawn'
    | 'inquiry_status_changed'
    | 'inquiry_deleted'
    | 'private_upload_deleted'
    | 'order_anonymized'
    | 'data_exported'
    | 'legal_hold_changed'
    | 'processing_restricted'
    | 'privacy_request_changed'
    | 'retention_setting_changed'
    | 'seed_imported'
    | 'seed_removed'
    | 'login_succeeded'
    | 'password_reset_requested';
  actorType: 'admin' | 'system' | 'webhook' | 'job' | 'customer' | 'seed';
  actorUser?: (number | null) | User;
  entityCollection: string;
  entityId: string;
  summary: string;
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  retainUntil: string;
  seed?: boolean | null;
  seedKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Welche Mail wann verschickt wurde (ohne Inhalt). Nur lesen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-log".
 */
export interface EmailLog {
  id: number;
  template:
    | 'order_confirmation'
    | 'prepayment_instructions'
    | 'prepayment_reminder'
    | 'prepayment_cancelled'
    | 'prepayment_received'
    | 'order_shipped'
    | 'pickup_ready'
    | 'withdrawal_receipt'
    | 'refund_confirmation'
    | 'oversold_apology'
    | 'inquiry_receipt'
    | 'complaint_repair_choice'
    | 'dispute_vsbg'
    | 'privacy_access_response'
    | 'privacy_erasure_response'
    | 'consent_withdrawal_confirmation'
    | 'admin_order_placed'
    | 'admin_prepayment_cancelled'
    | 'admin_withdrawal_received'
    | 'admin_inquiry_received'
    | 'admin_oversold'
    | 'admin_dispute_opened'
    | 'admin_refund_failed'
    | 'admin_revenue_guard'
    | 'admin_legal_review_due'
    | 'admin_monthly_close'
    | 'admin_alert'
    | 'admin_withdrawal_deadline'
    | 'admin_password_reset'
    | 'admin_privacy_request_due'
    | 'admin_legal_hold_review'
    | 'admin_compliance_docs_review';
  to: string;
  locale: 'de' | 'en';
  subject: string;
  status: 'queued' | 'sent' | 'failed' | 'suppressed';
  transport?: ('file' | 'smtp' | 'memory' | 'log') | null;
  messageId?: string | null;
  smtpResponse?: string | null;
  sentAt?: string | null;
  attempts?: number | null;
  lastError?: string | null;
  attachments?:
    | {
        filename: string;
        sha256: string;
        sizeBytes: number;
        id?: string | null;
      }[]
    | null;
  templateVersion?: string | null;
  bodySha256?: string | null;
  retainUntil: string;
  seed?: boolean | null;
  seedKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Nachweis von Einwilligungen und Vereinbarungen. Nur lesen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-log".
 */
export interface ConsentLog {
  id: number;
  purpose: 'carrier_email_forwarding' | 'deviation_agreement' | 'inquiry_privacy_notice';
  granted: boolean;
  textSnapshot: string;
  textSha256: string;
  snippetKey?: string | null;
  snippetVersion?: string | null;
  locale: 'de' | 'en';
  email: string;
  withdrawnAt?: string | null;
  retainUntil: string;
  seed?: boolean | null;
  seedKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Eingegangene Zahlungs-Ereignisse (ohne Personendaten). Nur lesen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-events".
 */
export interface WebhookEvent {
  id: number;
  provider: 'stripe' | 'mock';
  eventId: string;
  type: string;
  livemode: boolean;
  status: 'processing' | 'processed' | 'failed' | 'ignored';
  attempts: number;
  receivedAt?: string | null;
  processedAt?: string | null;
  lastError?: string | null;
  payloadSha256?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Nachweis aller Löschungen (ohne Inhalte, Namen oder E-Mail-Adressen). Nur lesen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deletion-log".
 */
export interface DeletionLog {
  id: number;
  entityCollection: string;
  entityId: string;
  ruleId: string;
  action: 'deleted' | 'anonymized' | 'restricted' | 'files_deleted';
  trigger: 'job' | 'privacy_request' | 'admin' | 'consent_withdrawn';
  taskSlug?: string | null;
  privacyRequestRef?: string | null;
  storageObjectsCount: number;
  executedAt: string;
  retainUntil: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'sendEmail';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'sendEmail') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'email-log';
        value: number | EmailLog;
      } | null)
    | ({
        relationTo: 'consent-log';
        value: number | ConsentLog;
      } | null)
    | ({
        relationTo: 'webhook-events';
        value: number | WebhookEvent;
      } | null)
    | ({
        relationTo: 'deletion-log';
        value: number | DeletionLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  showsPerson?: T;
  restricted?: T;
  source?: T;
  sourceRef?: T;
  enhance?: T;
  derivativesVersion?: T;
  placeholderDataUrl?: T;
  dominantColor?: T;
  seed?: T;
  seedKey?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        detail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        zoom?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  action?: T;
  actorType?: T;
  actorUser?: T;
  entityCollection?: T;
  entityId?: T;
  summary?: T;
  changes?: T;
  retainUntil?: T;
  seed?: T;
  seedKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-log_select".
 */
export interface EmailLogSelect<T extends boolean = true> {
  template?: T;
  to?: T;
  locale?: T;
  subject?: T;
  status?: T;
  transport?: T;
  messageId?: T;
  smtpResponse?: T;
  sentAt?: T;
  attempts?: T;
  lastError?: T;
  attachments?:
    | T
    | {
        filename?: T;
        sha256?: T;
        sizeBytes?: T;
        id?: T;
      };
  templateVersion?: T;
  bodySha256?: T;
  retainUntil?: T;
  seed?: T;
  seedKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-log_select".
 */
export interface ConsentLogSelect<T extends boolean = true> {
  purpose?: T;
  granted?: T;
  textSnapshot?: T;
  textSha256?: T;
  snippetKey?: T;
  snippetVersion?: T;
  locale?: T;
  email?: T;
  withdrawnAt?: T;
  retainUntil?: T;
  seed?: T;
  seedKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-events_select".
 */
export interface WebhookEventsSelect<T extends boolean = true> {
  provider?: T;
  eventId?: T;
  type?: T;
  livemode?: T;
  status?: T;
  attempts?: T;
  receivedAt?: T;
  processedAt?: T;
  lastError?: T;
  payloadSha256?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deletion-log_select".
 */
export interface DeletionLogSelect<T extends boolean = true> {
  entityCollection?: T;
  entityId?: T;
  ruleId?: T;
  action?: T;
  trigger?: T;
  taskSlug?: T;
  privacyRequestRef?: T;
  storageObjectsCount?: T;
  executedAt?: T;
  retainUntil?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendEmail".
 */
export interface TaskSendEmail {
  input: {
    emailLogId: number;
  };
  output: {
    status: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}